# Generated by Django 4.2.3 on 2023-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/blog-2.jpg', upload_to='blog/'),
        ),
    ]
